base_config: "base.yml"

# Args coming from the NVIDIA spreadsheet http://shortn/_W9CzVbtQde and
# third_party/py/maxtext/configs/a3/llama_2_7b.
hardware: "tpu"
model_name: "mixtral-8x7b"
enable_checkpointing: True
attention: "autoselected"
use_iota_embed: True
scan_layers: True
dataset_type: "synthetic"
logits_dot_in_fp32: False
num_experts: 8

tokenizer_path: assets/tokenizer.mistral
max_prefill_predict_length: 16 
max_target_length: 128
